version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      angular-dependencies:
        patterns:
          - '@angular/*'
          - '@angular-devkit/*'
          - 'typescript'
        update-types:
          - 'minor'
          - 'patch'
        allow:
          - dependency-type: 'all'
      dev-dependencies:
        dependency-type: 'development'
        exclude-patterns:
          - '@angular/*'
          - '@angular-devkit/*'
          - 'typescript'
