version: 2
updates:
  - package-ecosystem: 'npm' # See documentation for possible values
    directory: '/' # Location of package manifests
    schedule:
      interval: 'weekly'
    groups:
      angular-dependencies:
        patterns:
          - '@angular/*'
          - '@angular-devkit/*'
          - 'typescript'
        update-types:
          - 'minor'
          - 'patch'
      dev-dependencies: # Group for all devDependencies
        dependency-type: 'development'