import { compileFromFile } from 'json-schema-to-typescript';
import { existsSync, mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));

// Define paths
const rootDir = join(__dirname, '..');
const outputDir = join(rootDir, 'src', 'app', 'models', 'generated');
const schemaFile = join(rootDir, 'documentation', 'opengolfapi-course.schema.json');
const outputFile = join(outputDir, 'opengolfapi-course.ts');

// Remove the output directory if it exists
if (existsSync(outputDir)) {
  rmSync(outputDir, { recursive: true, force: true });
}

// Create the output directory
mkdirSync(outputDir, { recursive: true });

console.log('Generating TypeScript types from JSON Schema...');

try {
  // Compile JSON schema to TypeScript
  const ts = await compileFromFile(schemaFile, {
    // Adding a banner comment to warn other devs not to touch the generated file
    bannerComment: '/**\n* This file was automatically generated by json-schema-to-typescript.\n* DO NOT MODIFY IT BY HAND. Instead, modify the source JSON Schema file.\n*/',
    style: {
        singleQuote: true, // Example of hooking into its built-in prettier
    }
  });

  // Write the generated TypeScript to the output directory
  writeFileSync(outputFile, ts);

  console.log(`API generation completed successfully. Created: ${outputFile}`);
} catch (error) {
  console.error('Error generating types:', error);
  process.exit(1);
}